#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

/*
 * OPTIONS:
  MODE_NORMAL
  MODE_PWM_PC_8BIT
  MODE_PWM_PC_9BIT
  MODE_PWM_PC_10BIT
  MODE_CTC_OCR1A
  MODE_FAST_PWM_8BIT
  MODE_FAST_PWM_9BIT
  MODE_FAST_PWM_10BIT
  MODE_PWM_PFC_ICR1
  MODE_PWM_PFC_OCR1A
  MODE_PWM_PC_ICR1
  MODE_PWM_PC_OCR1A
  MODE_CTC_ICR1
  MODE_FAST_PWM_ICR1
  MODE_FAST_PWM_OCR1A
 *
 */
#define	TIMER1_MODE	MODE_FAST_PWM_ICR1

/*
 * OPTIONS:
  NO_CLOCK
  NO_PRESCALER
  DIV_8
  DIV_64
  DIV_256
  DIV_1024
  EXT_FALLING
  EXT_RISING
 *
 */
#define TIMER1_PRESCALER	DIV_8

#endif
